services:
  auth-template:
    image: auth-template
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
